# port to run the webserver on
webserver_port = 8080

# port to run the webserver on
admin_webserver_port = 8081

# database host # "localhost"
database_host = "mariadb"

# database port
database_port = 3306

# database user
database_user = "root"

# database user
database_password = "my-secret-pw"

# name of database where gocms's
# migrations was installed
database_name = "cms_db"

# image directory # "/home/enrique/Development/Go/gocms/media"
image_dir = "/gocms/media"

[[shortcodes]]
name = "img"
# must have function "HandleShortcode(arguments []string) -> string"
plugin = "plugins/image_shortcode.lua"

[[shortcodes]]
name = "table"
# must have function "HandleShortcode(arguments []string) -> string"
plugin = "plugins/table_shortcode.lua"


# ARRAY OF TABLES IN .TOML FILES:
# https://toml.io/en/v1.0.0#array-of-tables
