# port to run the webserver on
webserver_port = 8080

# port to run the webserver on
admin_webserver_port = 8081

# database host # "localhost"
database_host = "mariadb"

# database port
database_port = 3306

# database user
database_user = "root"

# database user
database_password = "my-secret-pw"

# name of database where gocms's
# migrations was installed
database_name = "cms_db"

# image directory # "/home/enrique/Development/Go/gocms/media"
image_dir = "/gocms/media"
