CREATE DATABASE cms_db;
USE cms_db;

CREATE TABLE IF NOT EXISTS posts (
    id INT NOT NULL AUTO_INCREMENT,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- content LONGBLOB NOT NULL,

CREATE TABLE IF NOT EXISTS images (
    uuid VARCHAR(36) DEFAULT(UUID()) PRIMARY KEY,
    name TEXT NOT NULL,
    alt TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
